export const SHOW_CONVERSATION = 'SHOW_CONVERSATION'
export const SHOW_CONVERSATION_LIST = 'SHOW_CONVERSATIONS_LIST'
export const CONVERSATION_CLICKED = 'CONVERSATION_CLICKED'

export const FETCH_USER_CONVERSATIONS = 'FETCH_USER_CONVERSATIONS'
export const ADD_NEW_CONVERSATION = 'ADD_NEW_CONVERSATION'

// Auth constants
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const FETCH_USER_DATA = 'FETCH_USER_DATA'
export const UPDATE_USER = 'UPDATE_USER'
